=== jorca11/XML2/archivo.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cotizacion [
    
    <!ELEMENT cotizacion(datos-cliente, detalle-cotizacion)>
        <!ATTLIST cotizacion folio CDATA #REQUIRED>
        <!ATTLIST cotizacion fecha CDATA #REQUIRED>

    <!ELEMENT datos-cliente (nombre, paterno, materno, email, telefono, direccion)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT paterno (#PCDATA)>
    <!ELEMENT materno (#PCDATA)>
    <!ELEMENT email (#PCDATA)>
    <!ELEMENT telefono (#PCDATA)>

    <!ELEMENT direccion (calle, colonia, municipio, pais)) >
    <!ELEMENT calle (#PCDATA)>
    <!ELEMENT colonia (#PCDATA)>
    <!ELEMENT municipio (#PCDATA)> 
        <!ATTLIST municipio ciudad (#PCDATA)> 
    <!ELEMENT pais #IMPLIED> 

    <!ELEMENT detalle-cotizacion (producto+)>
        <!ATTLIST detalle-cotizacion importe CDATA #REQUIRED>

    <!ELEMENT producto (nombreProducto, marca, precio, iva) >
        <!ATTLIST producto clave NMTOKEN #REQUIRED>
        <!ATTLIST producto marca IDREF #REQUIRED>
    <!ELEMENT nombreProducto CDATA #REQUIRED>
    <!ELEMENT precio CDATA #REQUIRED> 
    <!ELEMENT cantidad CDATA #REQUIRED>
    <!ELEMENT importe CDATA #REQUIRED>        
    <!ELEMENT iva (#PCDATA)>

    <!ELEMENT marca (id_marca, clave_marca, nombreMarca)>
    <!ELEMENT id_marca ID #REQUIRED>
    <!ELEMENT clave_marca NMTOKEN #REQUIRED>
    <!ELEMENT nombreMarca (#PCDATA)>

]>

=== jorca11/XML2/archivo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cotizacion SYSTEM "archivo.dtd">
<cotizacion folio="1" fecha="18/01/2021">
    <datos-cliente>
        <nombre>Maribel</nombre>
        <paterno>Barrera</paterno>
        <materno>Tabares</materno>
        <email>maribel@gmail.com</email>
        <telefono>5523556355</telefono>
        <direccion>
            <calle>San Marcos</calle>
            <colonia>Ticoman</colonia>
            <municipio ciudad="Guanaguato">
                Guanaguato
            </municipio>
            <pais></pais>
        </direccion>
    </datos-cliente>

    <detalle-cotizacion importe="800">  
        <producto clave="P001" marca="MEXIMEX">
            <nombreProducto>Loseta Piso Marmol</nombreProducto>
            <precio>100.00</precio>
            <cantidad>5</cantidad>
            <iva>16</iva>
            <importe>580</importe>
        </producto>

         <producto clave="S001" marca="N/A">
            <nombreProducto>Serivicio Instalaci√≥n</nombreProducto>
            <precio>220</precio>
            <cantidad>1</cantidad>
            <iva>0</iva>
            <importe>220</importe>
        </producto>
    </detalle-cotizacion>    
</cotizacion>
